trigger:
- develop

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'config'
    includeNuGetOrg: true
    nugetConfigPath: 'C:\Users\Administrator\AppData\Roaming\NuGet\NuGet.Config'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/MozaeekUserProfile.RestAPI.csproj'
    arguments: '-o $(System.DefaultWorkingDirectory)/Output'
    zipAfterPublish: false
    modifyOutputPath: true
    
