export const OTP_START = 'OTP_START';
export const OTP_START_SUCCESS = 'OTP_START_SUCCESS';
export const OTP_START_FAILED = 'OTP_START_FAILED';

export const OTP_VERIFY = 'OTP_VERIFY';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILED = 'OTP_VERIFY_FAILED';

export const RESET = 'RESET';
