export const Strings ={

    sliderTitle1:' امکان پرسش از مشاوران',
    sliderHint1:'  طرح پرسش و دریافت پاسخ مفید در موضوعات مختلف ',
    sliderTitle2:'  دریافت اخبار ویژه',
    sliderHint2:' مکان دریافت آخرین اخبار و رویدادهای ویژه اقتصادی',
    sliderTitle3:' شخصی سازی هوشمند',
    sliderHint3:' قابلیت شخصی سازی کلیه امکانات سامانه ',
    signup:'ورود',
    submit:'تایید',
    login:'ثبت نام',
    loginText:'لطفا شماره موبایل خود را وارد نمایید تا کد تایید برای شما ارسال گردد: ',
    mobile:'شماره موبایل',
    confirmCodeText:' لطفا کد چهار رقمی که از طریق پیامک دریافت نموده اید را وارد کنید: ',
    sendAgain:'تا ارسال مجدد ',
    placeholderInput:'جستجوی خدمت، مرکز، سازمان',
    dashboard:'میزکار',
    search:'جستجو...',
    announcement:'اعلانات',
    profile:'نمایش اطلاعات کاربری',
    Inventory:'موجودی:',
    recentTopic:'موضوع های پیشین شما',
    customize:'شخصی سازی',
    reward:'تخفیف و جایزه ',
    support:'پشتیبانی',
    messages:'پیام ها',
    completeId:'تکمیل شناسه ها',
}